export default [
  {
    _id: "CS1234",
    name: "React JS",
    number: "CS1234",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "D123",
    credits: 4,
    description: "Learn about the full stack software developer.",
    image: "/images/reactjs.png",
  },
  {
    _id: "CS2500",
    name: "Fundamentals of Computer Science II",
    number: "CS2500",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "D123",
    credits: 3,
    description:
      "The second fundamentals class for Computer Science: Java and introduction of Object-Oriented Dseign.",
    image: "/images/cs2500.png",
  },
  {
    _id: "CS2501",
    name: "Lab for Fundamentals of Computer Science II",
    number: "CS2501",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "D123",
    credits: 4,
    description:
      "A seminar-style period to collaborate closely with TAs and peers on CS2500 assignments",
    image: "/images/cs2501.png",
  },
  {
    _id: "ARTG1270",
    name: "Design Process and Practices",
    number: "ARTG1270",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "D134",
    credits: 3,
    description:
      "Learn about the various types of design: Experience, Interface, Informational, Graphic...",
    image: "/images/artg1270.png",
  },
  {
    _id: "ARTG1271",
    name: "Studio for Design Process and Practices",
    number: "ARTG1271",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "D134",
    credits: 3,
    description:
      "Apply your knowledge into studio-style projects with a smaller group of students and TAs.",
    image: "/images/artg1271.png",
  },
  {
    _id: "ARTF1123",
    name: "Color and Composition",
    number: "ARTF1123",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "D134",
    credits: 3,
    description:
      "Learn about the fundamentals of composition in the various forms of art.",
    image: "/images/artf1123.png",
  },
  {
    _id: "INAM2000",
    name: "Ethics in Creativity",
    number: "INAM2000",
    startDate: "2025-01-10",
    endDate: "2025-05-15",
    department: "Languages",
    credits: 3,
    description:
      "Discuss the ethics and moral considerations of creating art, code, and building creative solutions to existing problems.",
    image: "/images/inam2000.png",
    author: "654f9ec2ea7ead465908d1e3",
  },
];
